# Generated by Django 4.2.16 on 2024-09-14 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employees',
            old_name='first_name',
            new_name='full_name',
        ),
        migrations.RemoveField(
            model_name='employees',
            name='last_name',
        ),
    ]
