# Generated by Django 4.2.16 on 2024-09-14 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_rename_first_name_employees_full_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='photos',
            field=models.ImageField(blank=True, null=True, upload_to='employee_photos/'),
        ),
    ]
